spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv23li5UjErWFLZxC4ts
            client-secret: f72c7b55fd637ff0356a953f004181ee0a4ac60b
  data:
    cassandra:
      keyspace-name: main
      username: vxUyalUHhEahTMiqLettwYPe
      password: gfQwbXAYmeKLf4EMNPN1GZ2wIzdl+9OJY9-pMlf4jBAr6QfdcaiUk1+GJisqUJ4OKcgWmf.wZQdxjuP6a,Bj0Jy+79U-kx9NX1UDsGW5nBrW1lZ-UZTEg-vSzmT4F4.-
      schema-action: recreate-drop-unused
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

astra.db:
    id: 023b089b-0819-4a9d-9abd-5b6787c823d9
    region: asia-south1
    keyspace: main
    application.token: AstraCS:vxUyalUHhEahTMiqLettwYPe:2c34e626545bee015c1a0cc53a33bc961c6c782bb03f3e7fb8f99fe92bdfe74b

datastax.astra:
    secure-connect-bundle: secure-connect-inbox-app.zip
